version: 2
updates:
  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    commit-message:
      prefix: build
      prefix-development: chore
    groups:
      dev-dependencies:
        dependency-type: development

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    commit-message:
      prefix: build

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ci

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: build

  - package-ecosystem: docker
    directory: /web
    schedule:
      interval: weekly
    commit-message:
      prefix: build

  - package-ecosystem: pip
    directory: /DataLake/etl_pipeline
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    commit-message:
      prefix: build

  - package-ecosystem: docker
    directory: /DataLake/docker_image/spark
    schedule:
      interval: weekly
    commit-message:
      prefix: build

  - package-ecosystem: docker
    directory: /DataLake/docker_image/dagster
    schedule:
      interval: weekly
    commit-message:
      prefix: build

  - package-ecosystem: docker
    directory: /DataLake/docker_image/mlflow
    schedule:
      interval: weekly
    commit-message:
      prefix: build

  - package-ecosystem: docker
    directory: /DataLake/docker_image/streamlit
    schedule:
      interval: weekly
    commit-message:
      prefix: build
